// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package services is a generated GoMock package.
package services

import (
	"context"
	"encoding/json"
	"net/http"
	reflect "reflect"

	"developer.zopsmart.com/go/gofr/pkg/errors"
	"developer.zopsmart.com/go/gofr/pkg/service"

	models "developer.zopsmart.com/go/gofr/examples/using-http-service/models"
	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUser) Get(ctx *gofr.Context, name string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserMockRecorder) Get(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUser)(nil).Get), ctx, name)
}

type MockHTTPService struct {
	testID int
}

func New(testID int) MockHTTPService {
	return MockHTTPService{testID: testID}
}

func (m MockHTTPService) Get(ctx context.Context, api string, params map[string]interface{}) (*service.Response, error) {
	if m.testID == 0 {
		return nil, errors.MultipleErrors{StatusCode: http.StatusInternalServerError, Errors: []error{errors.Error("core error")}}
	}

	resp := service.Response{
		Body:       []byte(`{"data":{"name":"Vikash","company":"ZopSmart"}}`),
		StatusCode: http.StatusOK,
	}

	return &resp, nil
}

func (m MockHTTPService) Bind(resp []byte, i interface{}) error {
	if m.testID == 1 {
		return errors.Error("bind error")
	}

	return json.Unmarshal(resp, &i)
}
